server:
  port: 8083

spring:
  security:
    user:
      name: geniusconfig
      password: geniusconfig  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
    registerWithEureka: false
    fetchRegistry: false